sudo: required

language: cpp
compiler:
- gcc
- clang

before_install:
- git checkout $TRAVIS_BRANCH

- if [ $(bii-support/travis/git/is_last_commit_travis.sh) = "true" ] ; then exit 0 ; fi
- bii-support/travis/git/configure.sh

install:
- bii-support/travis/install/all-headless.sh

- export TRAVIS_CXX=$CXX

script:
- bii-support/linux/build/default.sh
- valgrind --leak-check=full "bin/${BII_USER}_${BLOCK_NAME}_test_main"

after_success:
- bii-support/travis/publish/biicode.sh

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - BLOCK_NAME=sl_core_application
  - BII_USER=azriel
  # BII_PASSWORD
  - secure: "b35ghAbsGFYhdUk1Sjx7ZsTP2vKIclJz7zr/KcbvN89uLfGrsEzDBAidYgmLY9O51PgWULPz8hVJLkYORBYlXAAJlF25Wm6eHTfPe0HaDRXmsPZZCYnYcEnJ0M1/cxfSbaNppXPWLiEjuvQNMBIn5SPLQ7MOV++oHfGAnmj6k3IpNZ7ZLybmyTN3eOVEHIhdGpMWLxg41MflprcF/mU2WRDMMYtIi+cgi0D0xqITV4uATlcxaGFlBd8Pyin1J+fnReoTzbMypjvcRchi6aiVFKT2hxuCL0XWV45dPIhUM9VU+EYvuP8chLwtH0UUYjRuKHoY3uxiVEhzCUKh+JB8wQE1SUlNUvfPo46YfsWqnW7BNeoePUNYVXXT4xOejNmroaSxOilOOyLSjfOcTyDjPc2+CvsXAfQghcyPVF9VZlmk4I0K+afuu10fUx3oRKnpIY76YiwH45S80zWJV2WoiB5EbvFpIr41yMviwkssuQfBUKNIwE3VLEUGCJa03NmDXb7EtOHMyM2/DbU+TlxKES6AUOcIqfcHpXw5eYZOj9sdNDYA4JjmfZrhhmepIsIOjjk9IaydW099lxmGBh2jljHeCLj/G2XfTMZ3PJxTg+jcwF2+yrNIlDd0eqHzvvh02/6xnrU6hp2xv917mKeSScGnsX2OPzKftjUAD6cIofk="
  # GITHUB_TOKEN
  - secure: "o7evUloBdEqJaBS9C8m4L/1vbrAJMW3rEBj13DpkHrF7L0Ca0avop3EEHl0irYCsdSnyw0cEZX4mUjZiiU/2QPXUHMfZg2U1SRBpNddh2fPt84TDGp8g0dluPOCGkogPdo7+QGtseqVglZoqsWlFKyBitGMDFLraofQwU94oVJukDCQbc/4Ardlw2o/5SfiApcIE3TaKTqFFOQE3/SyHtTyNqASYVcuyFNsnwOkU90MHvF3WzOvQJ4lNPWl3vp4Ku3cRl5Me/6TnAQP8JLjJutdKZf+57MKummAoG1dZLk+BZ62m4jDDSF8u7hePh/C0eJ1DXPAbohwC+rWehFjWL4sXgQvX+m7JONDnet7oqj1emHdzeVVS2QLz5W0JmZ5P7CflGniBFt5l2Ue2bfHjrvFCeqO7meRV1ZWrvuHGjn4je5llh6gkwvTNFu3VjSDch8CRgr9XEGoZxhw3h/+lARoH1iM9rUS2VuEySF+2AfGrloJlZskl4xlfv+Rv1qxn3EEWMx/p/iFJ/pR+sfWeLXzzulWr9uDpXAtRPhxh5I8Q1F6bRJYe/VisNi7xVj/CYflGfoq3JNWUxhnLCDdUM2CQOQ7whxHjHV06pOJ050evAzVtzyqoaok/tuURLDsyW8mG4K6rQFz1/AVPYNDDFXp9RkS0XvXx/9GoYP6IvHI="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON