language: cpp
compiler:
- gcc
- clang

before_install:
  # Don't build if the last commit was from travis
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- if [[ "$TRAVIS_COMMIT_MSG" = "$COMMIT_IGNORE_BUILD" ]]; then exit 0 ; fi

  # Configure git
- git config --global user.email "$USER_EMAIL"
- git config --global user.name "$USER_NAME"
- git config --global push.default simple
- git checkout $TRAVIS_BRANCH

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq

  # Install valgrind
- sudo apt-get install -qq valgrind

  # Install g++
- if [ "$CXX" = "g++" ]; then
    sudo apt-get install -qq g++-4.8;
    export CXX="g++-4.8" CC="gcc-4.8";
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
  fi

  # Install clang
- if [ "$CXX" = "clang++" ]; then
    sudo apt-get install -qq clang;
    export CXX="clang++" CC="clang";
    sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 90;
    sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 90;
  fi

  # Install Biicode
- wget -O bii-ubuntu64.deb http://www.biicode.com/downloads/latest/ubuntu64
- "(sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install"
- bii --version
- bii user $USER -p $BII_PASSWORD
- rm bii-ubuntu64.deb

  # Install CMake
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- rm -rf cmake-3.0.2-Linux-64
- rm cmake-3.0.2-Linux-64.tar.gz

- export TRAVIS_CXX=$CXX

script:
- bii init -l
- bii configure "-DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
- bii build
- valgrind --leak-check=full "bin/${USER}_${BLOCK_NAME}_test_main"

after_success:
  # Publish block
- if [[ -n $TRAVIS_TAG ]]; then bii publish -r --tag STABLE --versiontag $TRAVIS_TAG; fi
- if [[ -z $TRAVIS_TAG ]]; then bii publish -r; fi

  # If there are changes, commit them
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
- git add -A .
- git commit -m "$COMMIT_IGNORE_BUILD"
- git remote -v
- git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git
- git push

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - COMMIT_IGNORE_BUILD="Promoted version. ***travis***"
  - BLOCK_NAME=sl_core_application
  - USER=azriel
  # BII_PASSWORD
  - secure: "b35ghAbsGFYhdUk1Sjx7ZsTP2vKIclJz7zr/KcbvN89uLfGrsEzDBAidYgmLY9O51PgWULPz8hVJLkYORBYlXAAJlF25Wm6eHTfPe0HaDRXmsPZZCYnYcEnJ0M1/cxfSbaNppXPWLiEjuvQNMBIn5SPLQ7MOV++oHfGAnmj6k3IpNZ7ZLybmyTN3eOVEHIhdGpMWLxg41MflprcF/mU2WRDMMYtIi+cgi0D0xqITV4uATlcxaGFlBd8Pyin1J+fnReoTzbMypjvcRchi6aiVFKT2hxuCL0XWV45dPIhUM9VU+EYvuP8chLwtH0UUYjRuKHoY3uxiVEhzCUKh+JB8wQE1SUlNUvfPo46YfsWqnW7BNeoePUNYVXXT4xOejNmroaSxOilOOyLSjfOcTyDjPc2+CvsXAfQghcyPVF9VZlmk4I0K+afuu10fUx3oRKnpIY76YiwH45S80zWJV2WoiB5EbvFpIr41yMviwkssuQfBUKNIwE3VLEUGCJa03NmDXb7EtOHMyM2/DbU+TlxKES6AUOcIqfcHpXw5eYZOj9sdNDYA4JjmfZrhhmepIsIOjjk9IaydW099lxmGBh2jljHeCLj/G2XfTMZ3PJxTg+jcwF2+yrNIlDd0eqHzvvh02/6xnrU6hp2xv917mKeSScGnsX2OPzKftjUAD6cIofk="
  # GITHUB_TOKEN
  - secure: "o7evUloBdEqJaBS9C8m4L/1vbrAJMW3rEBj13DpkHrF7L0Ca0avop3EEHl0irYCsdSnyw0cEZX4mUjZiiU/2QPXUHMfZg2U1SRBpNddh2fPt84TDGp8g0dluPOCGkogPdo7+QGtseqVglZoqsWlFKyBitGMDFLraofQwU94oVJukDCQbc/4Ardlw2o/5SfiApcIE3TaKTqFFOQE3/SyHtTyNqASYVcuyFNsnwOkU90MHvF3WzOvQJ4lNPWl3vp4Ku3cRl5Me/6TnAQP8JLjJutdKZf+57MKummAoG1dZLk+BZ62m4jDDSF8u7hePh/C0eJ1DXPAbohwC+rWehFjWL4sXgQvX+m7JONDnet7oqj1emHdzeVVS2QLz5W0JmZ5P7CflGniBFt5l2Ue2bfHjrvFCeqO7meRV1ZWrvuHGjn4je5llh6gkwvTNFu3VjSDch8CRgr9XEGoZxhw3h/+lARoH1iM9rUS2VuEySF+2AfGrloJlZskl4xlfv+Rv1qxn3EEWMx/p/iFJ/pR+sfWeLXzzulWr9uDpXAtRPhxh5I8Q1F6bRJYe/VisNi7xVj/CYflGfoq3JNWUxhnLCDdUM2CQOQ7whxHjHV06pOJ050evAzVtzyqoaok/tuURLDsyW8mG4K6rQFz1/AVPYNDDFXp9RkS0XvXx/9GoYP6IvHI="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON